"use client";

import { FormEvent, useEffect, useState } from "react";
import { useRouter } from "next/navigation";
import { getSupabaseBrowserClient } from "../../../lib/supabase/browser";

type MediaRow = { id: string; storage_path: string; public_url: string; title: string; alt_text: string; category: string };
const categories = ["Product", "Factory", "Project", "Packing", "Material"];

export default function AdminMediaPage() {
  const router = useRouter(); const [rows, setRows] = useState<MediaRow[]>([]); const [file, setFile] = useState<File | null>(null); const [message, setMessage] = useState(""); const [busy, setBusy] = useState(false); const [form, setForm] = useState({ title: "", alt: "", category: "Product" });
  useEffect(() => { void loadRows(); }, []);
  async function loadRows() { const result = await getSupabaseBrowserClient().from("media_assets").select("id,storage_path,public_url,title,alt_text,category").order("created_at", { ascending: false }); if (result.error) setMessage(result.error.message); else setRows((result.data || []) as MediaRow[]); }
  async function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); if (!file) return setMessage("Please choose an image."); setBusy(true); setMessage(""); try { const client = getSupabaseBrowserClient(); if (!/^image\/(jpeg|png|webp)$/.test(file.type) || file.size > 10 * 1024 * 1024) throw new Error("Use a JPG, PNG, or WebP image smaller than 10 MB."); const path = `media/${crypto.randomUUID()}-${file.name.toLowerCase().replace(/[^a-z0-9.]+/g, "-")}`; const upload = await client.storage.from("factory-media").upload(path, file, { contentType: file.type }); if (upload.error) throw upload.error; const publicUrl = client.storage.from("factory-media").getPublicUrl(path).data.publicUrl; const result = await client.from("media_assets").insert({ storage_path: path, public_url: publicUrl, title: form.title, alt_text: form.alt, category: form.category }); if (result.error) throw result.error; setMessage("Saved."); setFile(null); setForm({ title: "", alt: "", category: "Product" }); await loadRows(); router.refresh(); } catch (error) { setMessage(error instanceof Error ? error.message : "Unable to save image."); } finally { setBusy(false); } }
  async function remove(row: MediaRow) { if (!window.confirm(`Delete ${row.title}?`)) return; const client = getSupabaseBrowserClient(); const storage = await client.storage.from("factory-media").remove([row.storage_path]); if (storage.error) return setMessage(storage.error.message); const result = await client.from("media_assets").delete().eq("id", row.id); if (result.error) setMessage(result.error.message); else await loadRows(); }
  async function signOut() { await getSupabaseBrowserClient().auth.signOut(); router.replace("/admin/login"); }
  return <main className="min-h-screen bg-paper px-5 py-12 md:px-12"><div className="mx-auto max-w-6xl"><div className="flex items-end justify-between"><div><p className="eyebrow-luxury">Media Library</p><h1 className="mt-3 font-title text-4xl text-ink">Upload reusable images</h1></div><button onClick={signOut} className="text-sm text-ink/60 underline">Sign out</button></div><form onSubmit={submit} className="mt-10 grid gap-4 rounded-[14px] border border-ink/10 bg-stone p-7 md:grid-cols-2"><label className="text-sm">Title<input required className="mt-2 w-full rounded border border-ink/15 bg-white p-3" value={form.title} onChange={(e) => setForm({ ...form, title: e.target.value })} /></label><label className="text-sm">Category<select className="mt-2 w-full rounded border border-ink/15 bg-white p-3" value={form.category} onChange={(e) => setForm({ ...form, category: e.target.value })}>{categories.map((category) => <option key={category}>{category}</option>)}</select></label><label className="text-sm md:col-span-2">Alt text<input required className="mt-2 w-full rounded border border-ink/15 bg-white p-3" value={form.alt} onChange={(e) => setForm({ ...form, alt: e.target.value })} /></label><label className="text-sm md:col-span-2">Image<input required accept="image/jpeg,image/png,image/webp" type="file" className="mt-2 block w-full text-sm" onChange={(e) => setFile(e.target.files?.[0] || null)} /></label><div className="md:col-span-2"><button disabled={busy} className="rounded-full bg-ink px-5 py-3 text-xs font-semibold uppercase tracking-[0.16em] text-white disabled:opacity-50">{busy ? "Saving…" : "Save image"}</button>{message ? <p className="mt-4 text-sm text-ink/70">{message}</p> : null}</div></form><section className="mt-12"><h2 className="font-title text-2xl text-ink">Existing images</h2><div className="mt-4 grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{rows.map((row) => <article key={row.id} className="card-luxury overflow-hidden bg-stone p-3"><img src={row.public_url} alt={row.alt_text} className="aspect-[4/3] w-full rounded object-cover" /><div className="p-3"><p className="text-xs uppercase tracking-[0.12em] text-ink/50">{row.category}</p><h3 className="mt-2 font-medium">{row.title}</h3><button onClick={() => remove(row)} className="mt-3 text-sm text-red-700 underline">Delete</button></div></article>)}</div></section></div></main>;
}
