import type { Metadata } from "next";
import Link from "next/link";
import PageShell from "../../components/PageShell";
import PageHero from "../../components/PageHero";
import JsonLd from "../../components/JsonLd";
import { absoluteUrl } from "../../lib/seo";

export const metadata: Metadata = { title: "Stone Buyer Resources", description: "Buyer guides for stone selection, hotel pricing, project checklists, quality control, export packing, and project references.", alternates: { canonical: absoluteUrl("/resources") } };
const resources = [["Buyer Guide", "/guides/stone-supplier-china", "How to assess a stone supplier before sending project information."], ["Hotel Stone Pricing", "/guides/hotel-stone-pricing", "The project variables that shape a useful hotel stone quotation."], ["Project Checklist", "/guides/stone-project-checklist", "The dimensions, quantities, and destination details that help a review."], ["QC & Delivery", "/guides/quality-control-delivery", "Questions to ask about inspection, finishing, and delivery coordination."], ["Export Packing", "/guides/export-packing-standards", "A practical reference for protective packing and loading preparation."], ["How We Work", "/how-we-work", "From project review and material matching to quotation and export preparation."], ["Project Brief Template", "/project-brief-template.txt", "Download a simple brief template before requesting a quotation."]];
const faqs = [["What should I send for a first quotation review?", "Send the project type, approximate quantity, dimensions or drawings, material direction, destination, and required timing. A rough brief is enough to start a practical review."], ["Do I need a finished CAD drawing?", "No. CAD, BOQ files, reference images, or rough dimensions can all help. The clearer the scope, the more specific the fabrication and quotation discussion can be."], ["Can you confirm the material before production?", "Material name, availability, thickness, finish, matching, and application suitability should be confirmed with the team before production is approved."], ["Do you support hotel and commercial projects?", "The site is structured for hotel, hospitality, commercial, residential, countertop, vanity, and custom stone inquiries. Scope and quantities are reviewed case by case."], ["How do I request pricing?", "Use the quotation form to send your project details and optional files, or contact the team through WhatsApp for an initial project conversation."]];
export default function ResourcesPage() { return <PageShell><main><JsonLd data={[{ "@context": "https://schema.org", "@type": "BreadcrumbList", itemListElement: [{ "@type": "ListItem", position: 1, name: "Home", item: absoluteUrl("/") }, { "@type": "ListItem", position: 2, name: "Resources", item: absoluteUrl("/resources") }] }, { "@context": "https://schema.org", "@type": "FAQPage", mainEntity: faqs.map(([question, answer]) => ({ "@type": "Question", name: question, acceptedAnswer: { "@type": "Answer", text: answer } })) }]} /><PageHero eyebrow="Buyer resources" title="Useful references for specifying and sourcing natural stone." description="Use these guides to prepare a stronger brief, compare fabrication paths, and move toward a clearer project conversation." backgroundImage="/generated/guides/buyer-guide-hero.png" /><section className="section-luxury bg-paper"><div className="container-luxury grid gap-5 md:grid-cols-2 lg:grid-cols-3">{resources.map(([title, href, copy]) => <Link key={href} href={href} className="card-luxury group flex min-h-[210px] flex-col justify-between p-7 transition hover:-translate-y-1"><div><p className="eyebrow-luxury">Reference note</p><h2 className="font-title mt-4 text-[1.65rem] leading-tight text-ink">{title}</h2><p className="body-luxury mt-4">{copy}</p></div><span className="text-cta-luxury mt-6">View guide</span></Link>)}</div></section><section className="section-luxury bg-stone"><div className="container-luxury max-w-4xl"><div className="section-intro"><p className="eyebrow-luxury">Frequently asked</p><h2 className="heading-lg text-left">Before you send the brief.</h2></div><div className="grid gap-4">{faqs.map(([question, answer]) => <details key={question} className="rounded-[14px] border border-ink/10 bg-paper px-6 py-5"><summary className="cursor-pointer list-none pr-8 font-title text-[1.2rem] font-medium uppercase leading-tight tracking-[0.03em] text-ink">{question}</summary><p className="body-luxury mt-4 max-w-3xl">{answer}</p></details>)}</div></div></section></main></PageShell>; }
