import Link from "next/link";
import type { EditorBlock } from "../lib/visual-editor";

export default function VisualPageRenderer({ blocks, preview = false, selectedId, onSelect }: { blocks: EditorBlock[]; preview?: boolean; selectedId?: string; onSelect?: (id: string) => void }) {
  const wrap = (block: EditorBlock, content: React.ReactNode) => <div className={`${selectedId === block.id ? "ring-2 ring-[#bf6c35]" : ""} ${onSelect ? "cursor-pointer" : ""}`} onClick={onSelect ? () => onSelect(block.id) : undefined}>{content}</div>;
  return <div className={preview ? "visual-preview" : "visual-page"}>{blocks.filter((block) => block.visible !== false).map((block) => {
    if (block.type === "hero") return wrap(block, <section data-editor-id={block.id} className="visual-block visual-hero relative overflow-hidden bg-ink text-white"><img src={block.image} alt="" className="absolute inset-0 h-full w-full object-cover opacity-55" /><div className="absolute inset-0 bg-ink/40" /><div className="relative mx-auto flex min-h-[480px] max-w-6xl flex-col justify-center px-6 py-20 md:px-12"><p className="eyebrow-luxury">{block.eyebrow}</p><h1 className="mt-5 max-w-4xl font-title text-5xl font-medium leading-tight md:text-7xl">{block.title}</h1><p className="mt-6 max-w-2xl text-base leading-8 text-white/78">{block.body}</p><span className="mt-8 w-fit rounded-full bg-white px-6 py-3 text-xs font-semibold uppercase tracking-[0.16em] text-ink">{block.buttonLabel}</span></div></section>);
    if (block.type === "text") return wrap(block, <section data-editor-id={block.id} className="visual-block section-luxury bg-paper"><div className="container-luxury"><p className="eyebrow-luxury">{block.eyebrow}</p><h2 className="mt-4 max-w-3xl font-title text-4xl text-ink">{block.title}</h2><p className="mt-5 max-w-3xl text-base leading-8 text-ink/68">{block.body}</p></div></section>);
    if (block.type === "card-grid") return wrap(block, <section data-editor-id={block.id} className="visual-block section-luxury bg-paper"><div className="container-luxury"><p className="eyebrow-luxury">{block.eyebrow}</p><h2 className="mt-4 max-w-3xl font-title text-4xl text-ink">{block.title}</h2><div className={`mt-10 grid gap-5 ${block.columns === 2 ? "md:grid-cols-2" : block.columns === 4 ? "md:grid-cols-2 xl:grid-cols-4" : "md:grid-cols-2 xl:grid-cols-3"}`}>{block.cards.map((card) => <article key={card.id} data-editor-card-id={card.id} className="card-luxury overflow-hidden bg-stone p-3"><img src={card.image} alt="" className="aspect-[4/3] w-full object-cover" /><div className="p-4"><h3 className="font-title text-2xl text-ink">{card.title}</h3><p className="mt-3 text-sm leading-7 text-ink/65">{card.body}</p><span className="mt-4 inline-block text-cta-luxury">View details</span></div></article>)}</div></div></section>);
    if (block.type === "process") return wrap(block, <section data-editor-id={block.id} className="visual-block section-luxury bg-stone"><div className="container-luxury"><p className="eyebrow-luxury">{block.eyebrow}</p><h2 className="mt-4 max-w-3xl font-title text-4xl text-ink">{block.title}</h2><div className="mt-10 grid gap-4 md:grid-cols-3 xl:grid-cols-5">{block.steps.map((step, index) => <article key={step.id} className="card-luxury bg-paper p-6"><p className="eyebrow-luxury">{String(index + 1).padStart(2, "0")}</p><h3 className="mt-4 font-title text-2xl text-ink">{step.title}</h3><p className="mt-3 text-sm leading-7 text-ink/65">{step.body}</p></article>)}</div></div></section>);
    return wrap(block, <section data-editor-id={block.id} className="visual-block section-luxury bg-paper"><div className="container-luxury flex flex-wrap items-center justify-between gap-7"><div><p className="eyebrow-luxury">{block.eyebrow}</p><h2 className="mt-4 max-w-3xl font-title text-4xl text-ink">{block.title}</h2></div><span className="btn-luxury-fill">{block.buttonLabel}</span></div></section>);
  })}</div>;
}
